// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Model;

namespace WebApi.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20190702113241_addTodoParent")]
    partial class addTodoParent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Model.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsDone");

                    b.Property<int?>("ParentTodoId");

                    b.Property<string>("Title");

                    b.HasKey("TodoId");

                    b.HasIndex("ParentTodoId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("WebApi.Model.Todo", b =>
                {
                    b.HasOne("WebApi.Model.Todo", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentTodoId");
                });
#pragma warning restore 612, 618
        }
    }
}
